gesdinet_jwt_refresh_token:
    user_identity_field: username
    refresh_token_class: App\Entity\RefreshToken
    user_provider: security.user.provider.concrete.in_database
    #ttl: 2592000
    ttl: 2592000
    single_use: true
    ttl_update: true
