# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    base_url: 'https://resources.geo-infrastructure-mg.com'
    pathImageEducation: '/home/qgis/projects/saisie/media/upload/ec_ecole/t_ec_01_infrastructure/'
    pathForNamePhotoEducation: 'media/upload/ec_ecole/t_ec_01_infrastructure/'
    #pathImageRoute: '/home/qgis/projects/saisie/media/upload/ro_route/t_ro_01_infrastructure/'
    #pathForNamePhotoRoute: 'media/upload/ro_route/t_ro_01_infrastructure/'
    pathImageRoute: '/home/qgis/projects/saisie/media/upload/se_route/t_se_ro_infrastructure/'
    pathForNamePhotoRoute: 'media/upload/se_route/t_se_ro_infrastructure/'
    pathPublic: '/images/infrastructures/'
    pathImageDalot: '/home/qgis/projects/saisie/media/upload/dar_dalot_route/t_dar_01_infrastructure/'
    pathForNamePhotoDalot: 'media/upload/dar_dalot_route/t_dar_01_infrastructure/'
    pathImagePont: '/home/qgis/projects/saisie/media/upload/pnr_pont_route/t_pnr_01_infrastructure/'
    pathForNamePhotoPont: 'media/upload/pnr_pont_route/t_pnr_01_infrastructure/'
    pathImageGareroutiere: '/home/qgis/projects/saisie/media/upload/gr_gare_routiere/t_gr_01_infrastructure/'
    pathForNamePhotoGareroutiere: 'media/upload/gr_gare_routiere/t_gr_01_infrastructure/'
    pathImageTrajetroute: '/home/qgis/projects/saisie/media/upload/tj_trajet_route/t_tj_01_infrastructure/'
    pathForNamePhotoTrajetroute: 'media/upload/tj_trajet_route/t_tj_01_infrastructure/'
    pathImageRadier: '/home/qgis/projects/saisie/media/upload/ra_radier/t_ra_01_infrastructure/'
    pathForNamePhotoRadier: 'media/upload/ra_radier/t_ra_01_infrastructure/'
    pathImageCunette: '/home/qgis/projects/saisie/media/upload/cu_cunette/t_cu_01_infrastructure/'
    pathForNamePhotoCunette: 'media/upload/cu_cunette/t_cu_01_infrastructure/'
    pathImageBac: '/home/qgis/projects/saisie/media/upload/bc_bac/t_bc_01_infrastructure/'
    pathForNamePhotoBac: 'media/upload/bc_bac/t_bc_01_infrastructure/'
    pathImageStationpesage: '/home/qgis/projects/saisie/media/upload/sp_station_pesage/t_sp_01_infrastructure/'
    pathForNamePhotoStationpesage: 'media/upload/sp_station_pesage/t_sp_01_infrastructure/'
    pathImageAntenne: '/home/qgis/projects/saisie/media/upload/ar_antenne_relai/t_ar_01_infrastructure/'
    pathForNamePhotoAntenne: 'media/upload/ar_antenne_relai/t_ar_01_infrastructure/'
    pathImageAssainissement: '/home/qgis/projects/saisie/media/upload/as_assainissement/t_as_01_infrastructure/'
    pathForNamePhotoAssainissement: 'media/upload/as_assainissement/t_as_01_infrastructure/'
    pathImageBarrageHydro: '/home/qgis/projects/saisie/media/upload/bh_barrage/t_bh_01_infrastructure/'
    pathForNamePhotoBarrageHydro: 'media/upload/bh_barrage/t_bh_01_infrastructure/'
    pathImageBatimentadministratif: '/home/qgis/projects/saisie/media/upload/ba_batiment_administratif/t_ba_01_infrastructure/'
    pathForNamePhotoBatimentadministratif: 'media/upload/ba_batiment_administratif/t_ba_01_infrastructure/'
    pathImageCentraleelectrique: '/home/qgis/projects/saisie/media/upload/ce_centrale_electrique/t_ce_01_infrastructure/'
    pathForNamePhotoCentraleelectrique: 'media/upload/ce_centrale_electrique/t_ce_01_infrastructure/'
    pathImageCentreculturel: '/home/qgis/projects/saisie/media/upload/cc_centre_culturel/t_cc_01_infrastructure/'
    pathForNamePhotoCentreculturel: 'media/upload/cc_centre_culturel/t_cc_01_infrastructure/'
    pathImageCheminfer: '/home/qgis/projects/saisie/media/upload/cf_chemin_de_fer/t_cf_01_infrastructure/'
    pathForNamePhotoCheminfer: 'media/upload/cf_chemin_de_fer/t_cf_01_infrastructure/'
    pathImageGareferoviaire: '/home/qgis/projects/saisie/media/upload/gf_gare_ferroviaire/t_gf_01_infrastructure/'
    pathForNamePhotoGareferoviaire: 'media/upload/gf_gare_ferroviaire/t_gf_01_infrastructure/'
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    App\Service\InfrastructureService:
        arguments: ['@security.token_storage', "@doctrine.orm.middleware_entity_manager", '@session', '@infrastructurerepository.service']
        public: true
    infrastructurerepository.service:
        class: App\Repository\InfrastructureRepository
    App\Service\LocalisationInfrastructureService:
        arguments: ['@security.token_storage', "@doctrine.orm.middleware_entity_manager", '@session', '@localisationinfrastructurerepository.service']
        public: true
    localisationinfrastructurerepository.service:
        class: App\Repository\LocalisationInfrastructureRepository
    App\Service\EducationService:
        arguments: ['@security.token_storage', "@doctrine.orm.middleware_entity_manager", '@session', '@educationrepository.service']
        public: true
    educationrepository.service:
        class: App\Repository\EducationRepository
    App\Service\RouteService:
        arguments: ['@security.token_storage', "@doctrine.orm.middleware_entity_manager", '@session', '@routerepository.service']
        public: true
    routerepository.service:
        class: App\Repository\RouteRepository
    App\Service\RefreshTokenService:
        arguments: ['@gesdinet.jwtrefreshtoken.authenticator', "@gesdinet.jwtrefreshtoken.user_provider", '@gesdinet.jwtrefreshtoken.security.authentication.success_handler', '@gesdinet.jwtrefreshtoken.security.authentication.failure_handler', '@gesdinet.jwtrefreshtoken.refresh_token_manager', 360, 'username',false, '@event_dispatcher']
        public: true
    dalotrepository.service:
        class: App\Repository\DalotRepository
    App\Service\DalotService:
        arguments: ['@security.token_storage', "@doctrine.orm.middleware_entity_manager", '@session', '@dalotrepository.service']
        public: true
    bacrepository.service:
        class: App\Repository\BacRepository
    App\Service\BacService:
        arguments: ['@security.token_storage', "@doctrine.orm.middleware_entity_manager", '@session', '@bacrepository.service']
        public: true
    pontrepository.service:
        class: App\Repository\PontRepository
    App\Service\PontService:
        arguments: ['@security.token_storage', "@doctrine.orm.middleware_entity_manager", '@session', '@pontrepository.service']
        public: true
    cunetterepository.service:
        class: App\Repository\CunetteRepository
    App\Service\CunetteService:
        arguments: ['@security.token_storage', "@doctrine.orm.middleware_entity_manager", '@session', '@cunetterepository.service']
        public: true
    Stationpesagerepository.service:
        class: App\Repository\StationpesageRepository
    App\Service\StationpesageService:
        arguments: ['@security.token_storage', "@doctrine.orm.middleware_entity_manager", '@session', '@Stationpesagerepository.service']
        public: true
    radierrepository.service:
        class: App\Repository\RadierRepository
    App\Service\RadierService:
        arguments: ['@security.token_storage', "@doctrine.orm.middleware_entity_manager", '@session', '@radierrepository.service']
        public: true
    gareroutiererepository.service:
        class: App\Repository\GareroutiereRepository
    App\Service\GareroutiereService:
        arguments: ['@security.token_storage', "@doctrine.orm.middleware_entity_manager", '@session', '@gareroutiererepository.service']
        public: true
    trajetrouterepository.service:
        class: App\Repository\TrajetrouteRepository
    App\Service\TrajetrouteService:
        arguments: ['@security.token_storage', "@doctrine.orm.middleware_entity_manager", '@session', '@trajetrouterepository.service']
        public: true
    antennerepository.service:
        class: App\Repository\AntenneRepository
    App\Service\AntenneService:
        arguments: ['@security.token_storage', "@doctrine.orm.middleware_entity_manager", '@session', '@antennerepository.service']
        public: true
    assainissementrepository.service:
        class: App\Repository\AssainissementRepository
    App\Service\AssainissementService:
        arguments: ['@security.token_storage', "@doctrine.orm.middleware_entity_manager", '@session', '@assainissementrepository.service']
        public: true
    barragehydrorepository.service:
        class: App\Repository\BarragehydroRepository
    App\Service\BarragehydroService:
        arguments: ['@security.token_storage', "@doctrine.orm.middleware_entity_manager", '@session', '@barragehydrorepository.service']
        public: true
    batimentadministratifrepository.service:
        class: App\Repository\BatimentadministratifRepository
    App\Service\BatimentadministratifService:
        arguments: ['@security.token_storage', "@doctrine.orm.middleware_entity_manager", '@session', '@batimentadministratifrepository.service']
        public: true
    centraleeletctriquerepository.service:
        class: App\Repository\CentraleelectriqueRepository
    App\Service\CentraleelectriqueService:
        arguments: ['@security.token_storage', "@doctrine.orm.middleware_entity_manager", '@session', '@centraleeletctriquerepository.service']
        public: true
    centreculturelrepository.service:
        class: App\Repository\CentreculturelRepository
    App\Service\CentreculturelService:
        arguments: ['@security.token_storage', "@doctrine.orm.middleware_entity_manager", '@session', '@centreculturelrepository.service']
        public: true 
    cheminferrepository.service:
        class: App\Repository\CheminferRepository
    App\Service\CheminferService:
        arguments: ['@security.token_storage', "@doctrine.orm.middleware_entity_manager", '@session', '@cheminferrepository.service']
        public: true
    gareferoviairerepository.service:
        class: App\Repository\GareferoviaireRepository
    App\Service\GareferoviaireService:
        arguments: ['@security.token_storage', "@doctrine.orm.middleware_entity_manager", '@session', '@gareferoviairerepository.service']
        public: true
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
