<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSRa9FSL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSRa9FSL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSRa9FSL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSRa9FSL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSRa9FSL\App_KernelDevDebugContainer([
    'container.build_hash' => 'SRa9FSL',
    'container.build_id' => 'ab492b01',
    'container.build_time' => 1668615401,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSRa9FSL');
