<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFb6y1cJ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFb6y1cJ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFb6y1cJ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFb6y1cJ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFb6y1cJ\App_KernelDevDebugContainer([
    'container.build_hash' => 'Fb6y1cJ',
    'container.build_id' => '8df6ce21',
    'container.build_time' => 1670753379,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFb6y1cJ');
