<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHTDxxww\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHTDxxww/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHTDxxww.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHTDxxww\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHTDxxww\App_KernelDevDebugContainer([
    'container.build_hash' => 'HTDxxww',
    'container.build_id' => 'd2fb58f7',
    'container.build_time' => 1669093516,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHTDxxww');
